# @package _global_
module:
  _target_: emg2qwerty.lightning.CNNCTCModule
  in_features: 528
  mlp_features: [384]
  conv_channels: [192, 192, 192, 192, 192]
  kernel_widths: [9, 9, 9, 9, 9]
  dilations: [1, 2, 4, 8, 16]
  dropout: 0.15

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]